version = "1.0.0"
owner = "etienne@scalingo.com"
team = "IST"
description = "This buildpack manage the installation of Logstash"
languages = ["shell"]
destination_server = []
flags = ["buildpack"]
dependencies = []
